package Hibernate;
// Generated Sep 7, 2015 3:42:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Artista generated by hbm2java
 */
public class Artista  implements java.io.Serializable {


     private Integer idArtista;
     private Usuario usuario;
     private Date createTime;
     private String nombre;
     private String telefono;
     private String direccion;
     private Set estampados = new HashSet(0);

    public Artista() {
    }

	
    public Artista(Usuario usuario) {
        this.usuario = usuario;
    }
    public Artista(Usuario usuario, Date createTime, String nombre, String telefono, String direccion, Set estampados) {
       this.usuario = usuario;
       this.createTime = createTime;
       this.nombre = nombre;
       this.telefono = telefono;
       this.direccion = direccion;
       this.estampados = estampados;
    }
   
    public Integer getIdArtista() {
        return this.idArtista;
    }
    
    public void setIdArtista(Integer idArtista) {
        this.idArtista = idArtista;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getEstampados() {
        return this.estampados;
    }
    
    public void setEstampados(Set estampados) {
        this.estampados = estampados;
    }




}


