package Hibernate;
// Generated Sep 7, 2015 3:42:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private Integer idcompra;
     private Cliente cliente;
     private Date fecha;
     private Set compraHasEstampados = new HashSet(0);

    public Compra() {
    }

	
    public Compra(Cliente cliente) {
        this.cliente = cliente;
    }
    public Compra(Cliente cliente, Date fecha, Set compraHasEstampados) {
       this.cliente = cliente;
       this.fecha = fecha;
       this.compraHasEstampados = compraHasEstampados;
    }
   
    public Integer getIdcompra() {
        return this.idcompra;
    }
    
    public void setIdcompra(Integer idcompra) {
        this.idcompra = idcompra;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getCompraHasEstampados() {
        return this.compraHasEstampados;
    }
    
    public void setCompraHasEstampados(Set compraHasEstampados) {
        this.compraHasEstampados = compraHasEstampados;
    }




}


