package Hibernate;
// Generated Sep 7, 2015 3:42:23 PM by Hibernate Tools 4.3.1



/**
 * CompraHasEstampado generated by hbm2java
 */
public class CompraHasEstampado  implements java.io.Serializable {


     private CompraHasEstampadoId id;
     private Compra compra;
     private Estampado estampado;
     private Integer cantidad;
     private String tono;
     private String talla;
     private String estilo;
     private String ubicacion;
     private String texto;
     private Integer rating;
     
   

    public CompraHasEstampado() {
    }

	
    public CompraHasEstampado(CompraHasEstampadoId id, Compra compra, Estampado estampado) {
        this.id = id;
        this.compra = compra;
        this.estampado = estampado;
    }
    public CompraHasEstampado(CompraHasEstampadoId id, Compra compra, Estampado estampado, Integer cantidad, String tono, String talla, String estilo, String ubicacion, String texto) {
       this.id = id;
       this.compra = compra;
       this.estampado = estampado;
       this.cantidad = cantidad;
       this.tono = tono;
       this.talla = talla;
       this.estilo = estilo;
       this.ubicacion = ubicacion;
       this.texto = texto;
    }
   
    public CompraHasEstampadoId getId() {
        return this.id;
    }
    
    public void setId(CompraHasEstampadoId id) {
        this.id = id;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Estampado getEstampado() {
        return this.estampado;
    }
    
    public void setEstampado(Estampado estampado) {
        this.estampado = estampado;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public String getTono() {
        return this.tono;
    }
    
    public void setTono(String tono) {
        this.tono = tono;
    }
    public String getTalla() {
        return this.talla;
    }
    
    public void setTalla(String talla) {
        this.talla = talla;
    }
    public String getEstilo() {
        return this.estilo;
    }
    
    public void setEstilo(String estilo) {
        this.estilo = estilo;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }

 public Integer getRating() {
        return rating;
    }

    public void setRating(Integer rating) {
        this.rating = rating;
    }


}


