package Hibernate;
// Generated Sep 7, 2015 3:42:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estampado generated by hbm2java
 */
public class Estampado  implements java.io.Serializable {


     private Integer idestampado;
     private Artista artista;
     private String nombre;
     private String descripcion;
     private Integer popularidad;
     private Integer valor;
     private Set temas = new HashSet(0);
     private Set compraHasEstampados = new HashSet(0);
     private Set imagens = new HashSet(0);

    public Estampado() {
    }

	
    public Estampado(Artista artista) {
        this.artista = artista;
    }
    public Estampado(Artista artista, String nombre, String descripcion, Integer popularidad, Integer valor, Set temas, Set compraHasEstampados, Set imagens) {
       this.artista = artista;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.popularidad = popularidad;
       this.valor = valor;
       this.temas = temas;
       this.compraHasEstampados = compraHasEstampados;
       this.imagens = imagens;
    }
   
    public Integer getIdestampado() {
        return this.idestampado;
    }
    
    public void setIdestampado(Integer idestampado) {
        this.idestampado = idestampado;
    }
    public Artista getArtista() {
        return this.artista;
    }
    
    public void setArtista(Artista artista) {
        this.artista = artista;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getPopularidad() {
        return this.popularidad;
    }
    
    public void setPopularidad(Integer popularidad) {
        this.popularidad = popularidad;
    }
    public Integer getValor() {
        return this.valor;
    }
    
    public void setValor(Integer valor) {
        this.valor = valor;
    }
    public Set getTemas() {
        return this.temas;
    }
    
    public void setTemas(Set temas) {
        this.temas = temas;
    }
    public Set getCompraHasEstampados() {
        return this.compraHasEstampados;
    }
    
    public void setCompraHasEstampados(Set compraHasEstampados) {
        this.compraHasEstampados = compraHasEstampados;
    }
    public Set getImagens() {
        return this.imagens;
    }
    
    public void setImagens(Set imagens) {
        this.imagens = imagens;
    }




}


