package Hibernate;
// Generated Sep 7, 2015 3:42:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idusuario;
     private String usuario;
     private String password;
     private Date createTime;
     private Set clientes = new HashSet(0);
     private Set artistas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String usuario, String password) {
        this.usuario = usuario;
        this.password = password;
    }
    public Usuario(String usuario, String password, Date createTime, Set clientes, Set artistas) {
       this.usuario = usuario;
       this.password = password;
       this.createTime = createTime;
       this.clientes = clientes;
       this.artistas = artistas;
    }
   
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getArtistas() {
        return this.artistas;
    }
    
    public void setArtistas(Set artistas) {
        this.artistas = artistas;
    }




}


