package proyecto.model;
// Generated 21/03/2019 05:51:36 PM by Hibernate Tools 4.3.1



/**
 * Apuesta generated by hbm2java
 */
public class Apuesta  implements java.io.Serializable {


     private Integer idApuesta;
     private String nombreApuesta;
     private Integer idDeporte;
     private Integer idPartido;
     private String marcador;
     private String activo;

    public Apuesta() {
    }

    public Apuesta(String nombreApuesta, Integer idDeporte, Integer idPartido, String marcador, String activo) {
       this.nombreApuesta = nombreApuesta;
       this.idDeporte = idDeporte;
       this.idPartido = idPartido;
       this.marcador = marcador;
       this.activo = activo;
    }
   
    public Integer getIdApuesta() {
        return this.idApuesta;
    }
    
    public void setIdApuesta(Integer idApuesta) {
        this.idApuesta = idApuesta;
    }
    public String getNombreApuesta() {
        return this.nombreApuesta;
    }
    
    public void setNombreApuesta(String nombreApuesta) {
        this.nombreApuesta = nombreApuesta;
    }
    public Integer getIdDeporte() {
        return this.idDeporte;
    }
    
    public void setIdDeporte(Integer idDeporte) {
        this.idDeporte = idDeporte;
    }
    public Integer getIdPartido() {
        return this.idPartido;
    }
    
    public void setIdPartido(Integer idPartido) {
        this.idPartido = idPartido;
    }
    public String getMarcador() {
        return this.marcador;
    }
    
    public void setMarcador(String marcador) {
        this.marcador = marcador;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }




}


