package proyecto.model;
// Generated 21/03/2019 05:51:36 PM by Hibernate Tools 4.3.1



/**
 * Deporte generated by hbm2java
 */
public class Deporte  implements java.io.Serializable {


     private Integer idDeporte;
     private String deporte;

    public Deporte() {
    }

    public Deporte(String deporte) {
       this.deporte = deporte;
    }
   
    public Integer getIdDeporte() {
        return this.idDeporte;
    }
    
    public void setIdDeporte(Integer idDeporte) {
        this.idDeporte = idDeporte;
    }
    public String getDeporte() {
        return this.deporte;
    }
    
    public void setDeporte(String deporte) {
        this.deporte = deporte;
    }




}


