package proyecto.model;
// Generated 21/03/2019 05:51:36 PM by Hibernate Tools 4.3.1



/**
 * Boleteria generated by hbm2java
 */
public class Boleteria  implements java.io.Serializable {


     private Integer idBoleteria;
     private Integer maxBoletas;
     private String precioBoleta;
     private String tipoBoleta;

    public Boleteria() {
    }

    public Boleteria(Integer idBoleteria, Integer maxBoletas, String precioBoleta, String tipoBoleta) {
        this.idBoleteria = idBoleteria;
        this.maxBoletas = maxBoletas;
        this.precioBoleta = precioBoleta;
        this.tipoBoleta = tipoBoleta;
    }

    public Integer getIdBoleteria() {
        return idBoleteria;
    }

    public void setIdBoleteria(Integer idBoleteria) {
        this.idBoleteria = idBoleteria;
    }

    public Integer getMaxBoletas() {
        return maxBoletas;
    }

    public void setMaxBoletas(Integer maxBoletas) {
        this.maxBoletas = maxBoletas;
    }

    public String getPrecioBoleta() {
        return precioBoleta;
    }

    public void setPrecioBoleta(String precioBoleta) {
        this.precioBoleta = precioBoleta;
    }

    public String getTipoBoleta() {
        return tipoBoleta;
    }

    public void setTipoBoleta(String tipoBoleta) {
        this.tipoBoleta = tipoBoleta;
    }


}


