package proyecto.model;
// Generated 21/03/2019 05:51:36 PM by Hibernate Tools 4.3.1



/**
 * Equipos generated by hbm2java
 */
public class Equipos  implements java.io.Serializable {


     private Integer idEquipos;
     private String nombreEquipo;
     private Integer idDeporte;

    public Equipos() {
    }

    public Equipos(String nombreEquipo, Integer idDeporte) {
       this.nombreEquipo = nombreEquipo;
       this.idDeporte = idDeporte;
    }
   
    public Integer getIdEquipos() {
        return this.idEquipos;
    }
    
    public void setIdEquipos(Integer idEquipos) {
        this.idEquipos = idEquipos;
    }
    public String getNombreEquipo() {
        return this.nombreEquipo;
    }
    
    public void setNombreEquipo(String nombreEquipo) {
        this.nombreEquipo = nombreEquipo;
    }
    public Integer getIdDeporte() {
        return this.idDeporte;
    }
    
    public void setIdDeporte(Integer idDeporte) {
        this.idDeporte = idDeporte;
    }




}


