package proyecto.model;
// Generated 21/03/2019 05:51:36 PM by Hibernate Tools 4.3.1



/**
 * Rifa generated by hbm2java
 */
public class Rifa  implements java.io.Serializable {


     private Integer idRifa;
     private Integer maxParticipantes;
     private String premios;
     private String formaGanar;

    public Rifa() {
    }

    public Rifa(Integer maxParticipantes, String premios, String formaGanar) {
       this.maxParticipantes = maxParticipantes;
       this.premios = premios;
       this.formaGanar = formaGanar;
    }
   
    public Integer getIdRifa() {
        return this.idRifa;
    }
    
    public void setIdRifa(Integer idRifa) {
        this.idRifa = idRifa;
    }
    public Integer getMaxParticipantes() {
        return this.maxParticipantes;
    }
    
    public void setMaxParticipantes(Integer maxParticipantes) {
        this.maxParticipantes = maxParticipantes;
    }
    public String getPremios() {
        return this.premios;
    }
    
    public void setPremios(String premios) {
        this.premios = premios;
    }
    public String getFormaGanar() {
        return this.formaGanar;
    }
    
    public void setFormaGanar(String formaGanar) {
        this.formaGanar = formaGanar;
    }




}


