package proyecto.model;
// Generated 21/03/2019 05:51:36 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Torneo generated by hbm2java
 */
public class Torneo  implements java.io.Serializable {


     private Integer idTorneo;
     private String nombreTorneo;
     private String idEquipo;
     private Date fechaInicio;
     private Date fechaFin;
     private String partidosTorneo;

    public Torneo() {
    }

    public Torneo(String nombreTorneo, String idEquipo, Date fechaInicio, Date fechaFin, String partidosTorneo) {
       this.nombreTorneo = nombreTorneo;
       this.idEquipo = idEquipo;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.partidosTorneo = partidosTorneo;
    }

    public Integer getIdTorneo() {
        return idTorneo;
    }

    public void setIdTorneo(Integer idTorneo) {
        this.idTorneo = idTorneo;
    }

    public String getNombreTorneo() {
        return nombreTorneo;
    }

    public void setNombreTorneo(String nombreTorneo) {
        this.nombreTorneo = nombreTorneo;
    }

    public String getIdEquipo() {
        return idEquipo;
    }

    public void setIdEquipo(String idEquipo) {
        this.idEquipo = idEquipo;
    }

    public Date getFechaInicio() {
        return fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    public Date getFechaFin() {
        return fechaFin;
    }

    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    public String getPartidosTorneo() {
        return partidosTorneo;
    }

    public void setPartidosTorneo(String partidosTorneo) {
        this.partidosTorneo = partidosTorneo;
    }
   
   



}


